version: '3.4'

services:
  formulaone.api:
    build: 
      context: .
      dockerfile: ./src/FormulaOne.Api/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: formulaone
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql  
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1!
    volumes:
      - formulaone-mssql-data:/var/opt/mssql

volumes:
  formulaone-mssql-data:
