version: '3.4'

services:
  formulaone.api:
    container_name: formulaone
    build: 
      context: .
      dockerfile: ./src/FormulaOne.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_CONTAINER_PATH}/${CERTIFICATE_FILENAME}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_HTTPS_PORT=5001
      - MSSQL_HOST=${MSSQL_HOST}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DB_NAME=${MSSQL_DB_NAME}
    volumes:
      - ${CERTIFICATE_HOST_DIRECTORY}:${CERTIFICATE_CONTAINER_PATH}
    depends_on:
      - mssql
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU17-ubuntu-22.04
    container_name: mssql  
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - formulaone-mssql-data:/var/opt/mssql

volumes:
  formulaone-mssql-data:
